name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull FEniCS Docker image
      run: docker pull quay.io/fenicsproject/stable:latest

    - name: Run commands inside the FEniCS container
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/fenics/shared quay.io/fenicsproject/stable:latest /bin/bash -c "\
          pip3 list && \
          pip3 install pandas sklearn tabulate && \
          python3 /home/fenics/shared/main.py \
        "

