name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dolfin-bin libdolfin-dev libdolfin-dev-common libdolfin2019.2 python3-dijitso python3-dolfin python3-dolfin-real python3-ffc python3-ufl

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fenics numpy scipy matplotlib jsonschema pandas sklearn tabulate

    - name: Run main.py
      run: python3 main.py

