name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull FEniCS Docker image
      run: docker pull quay.io/fenicsproject/stable:latest

    - name: Run container
      run: docker run -d --name fenics-container -v ${{ github.workspace }}:/home/fenics/shared quay.io/fenicsproject/stable:latest sleep infinity

    - name: List installed Python packages
      run: docker exec fenics-container pip3 list

#    - name: Install additional Python packages
#      run: docker exec fenics-container pip3 install numpy scipy matplotlib jsonschema pandas sklearn tabulate

    - name: Install additional Python packages
      run: docker exec fenics-container pip3 install pandas sklearn tabulate

    - name: Execute main.py inside the container
      run: docker exec fenics-container python3 /home/fenics/shared/main.py

    - name: Stop container
      run: docker stop fenics-container

