name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

 #   - name: Set up Python 3.x
 #     uses: actions/setup-python@v2
 #     with:
 #       python-version: 3.10.12

# - name: Set PYTHONPATH
#      run: echo "PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages" >> $GITHUB_ENV


    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dolfin-bin libdolfin-dev libdolfin-dev-common libdolfin2019.2 python3-dijitso python3-dolfin python3-dolfin-real python3-ffc python3-ufl python3-tabulate python3-tables python3-scipy python3-petsc4py python3-pandas python3-numpy python3-sklearn python3-jsonschema python3-matplotlib python3-mshr


    - name: List site-packages
      run: |
        ls $(python -c "import site; print(site.getsitepackages()[0])")
        pip list

    - name: Run main.py
      run: python3 main.py

